COMPONENT_INCDIRS := src/include
COMPONENT_SRCDIRS := src
COMPONENT_DOXYGEN_INPUT := src/include

#
COMPONENT_VARS += ENABLE_NVS_ENCRYPTION
ENABLE_NVS_ENCRYPTION ?= 0
ifeq ($(ENABLE_NVS_ENCRYPTION),1)
COMPONENT_CXXFLAGS += -DENABLE_NVS_ENCRYPTION=1
COMPONENT_SRCDIRS += src/enc
endif

ifneq ($(SMING_ARCH),Esp32)
COMPONENT_INCDIRS += src/esp32
endif

#
COMPONENT_VARS += ENABLE_NVS_DEBUGCHECK
ENABLE_NVS_DEBUGCHECK ?= 0
ifeq ($(ENABLE_NVS_DEBUGCHECK),1)
COMPOONENT_CXXFLAGS += -DENABLE_NVS_DEBUGCHECK=1
endif
