COMPONENT_INCDIRS := src/include
COMPONENT_SRCDIRS := src

COMPONENT_VARS += ENABLE_NVS_ENCRYPTION
ENABLE_NVS_ENCRYPTION ?= 0

ifeq ($(ENABLE_NVS_ENCRYPTION),1)
COMPONENT_CXXFLAGS += -DENABLE_NVS_ENCRYPTION=1
COMPONENT_SRCDIRS += src/enc
endif

ifneq ($(SMING_ARCH),Esp32)
COMPONENT_INCDIRS += src/esp32
endif
